<?php

return [
    'defaults' => [
        'supervisor-aws' => [
            'connection' => 'redis',
            'queue' => ['aws'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 30,
            'minProcesses' => 1,
            'balanceMaxShift' => 10,
            'balanceCooldown' => 3,
            'maxTime' => 3600,
            'maxJobs' => 1000,
            'memory' => 256,
            'tries' => 3,
            'timeout' => 120,
            'nice' => 0,
        ],
        'supervisor-default' => [
            'connection' => 'redis',
            'queue' => ['default'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 3,
            'maxTime' => 3600,
            'maxJobs' => 1000,
            'memory' => 256,
            'tries' => 3,
            'timeout' => 120,
            'nice' => 0,
        ],
        'supervisor-pbf' => [
            'connection' => 'redis',
            'queue' => ['pbf'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 10,
            'minProcesses' => 1,
            'balanceMaxShift' => 10,
            'balanceCooldown' => 3,
            'maxTime' => 3600,
            'maxJobs' => 1000,
            'memory' => 256,
            'tries' => 5,
            'timeout' => 180,
            'nice' => 0,
        ],
        'supervisor-dem' => [
            'connection' => 'redis',
            'queue' => ['dem'],
            'balance' => 'auto',
            'autoScalingStrategy' => 'time',
            'maxProcesses' => 6,
            'minProcesses' => 1,
            'balanceMaxShift' => 3,
            'balanceCooldown' => 3,
            'maxTime' => 3600,
            'maxJobs' => 1000,
            'memory' => 256,
            'tries' => 3,
            'timeout' => 120,
            'nice' => 0,
        ],
        'supervisor-layers' => [
            'connection' => 'redis',
            'queue' => ['layers'],
            'balance' => 'simple',
            'maxProcesses' => 3,
            'maxTime' => 3600,
            'maxJobs' => 500,
            'memory' => 256,
            'tries' => 3,
            'timeout' => 120,
            'nice' => 0,
        ],
    ],

    'environments' => [
        'local' => [
            'supervisor-default' => [
                'balance' => 'simple',
                'maxProcesses' => 30,
            ],
        ],
        'develop' => [
            'supervisor-default' => [
                'maxProcesses' => 30,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 10,
                'balanceCooldown' => 3,
            ],
            'supervisor-pbf' => [
                'maxProcesses' => 6,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 3,
                'balanceCooldown' => 2,
            ],
            'supervisor-layers' => [
                'maxProcesses' => 4,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 2,
                'balanceCooldown' => 2,
            ],
        ],
        'staging' => [
            'supervisor-default' => [
                'maxProcesses' => 30,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 10,
                'balanceCooldown' => 3,
            ],
            'supervisor-pbf' => [
                'maxProcesses' => 6,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 3,
                'balanceCooldown' => 2,
            ],
            'supervisor-layers' => [
                'maxProcesses' => 4,
                'minProcesses' => 1,
                'balance' => 'auto',
                'autoScalingStrategy' => 'time',
                'balanceMaxShift' => 2,
                'balanceCooldown' => 2,
            ],
        ],
    ],
];
